function(LOAD_VARS FILE)
    set(OPTS "Following configuration was loaded from ${FILE}")
    file(STRINGS ${FILE} CONTENTS)
    foreach(NAME_AND_VALUE ${CONTENTS})
      # Strip leading spaces
      string(REGEX REPLACE "^[ ]+" "" NAME_AND_VALUE "${NAME_AND_VALUE}")
      if (NAME_AND_VALUE MATCHES "^#")
        continue()
      endif()
      # Find variable name
      string(REGEX MATCH "^[^=]+" NAME "${NAME_AND_VALUE}")
      # Find the value
      string(REPLACE "${NAME}=" "" QUOTED_VALUE "${NAME_AND_VALUE}")
      string(REPLACE "\"" "" VALUE "${QUOTED_VALUE}")
      # Set the variable
      if (NOT "${VALUE}" STREQUAL "")
        set(${NAME} "${VALUE}" CACHE STRING "" FORCE)
      endif()
      message(STATUS "    ${NAME}=${VALUE}")
    endforeach()
endfunction()

function(SET_PROJECT_OPTIONS)
    load_vars(project.cfg)
endfunction()

function(SET_COMPILER_OPTIONS)
    if (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
        load_vars(opt_msvc.cfg)
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU")
        load_vars(opt_gcc.cfg)
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        load_vars(opt_clang.cfg)
    endif()
endfunction()
