if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
  add_compile_definitions(PROJ_OS_WINDOWS)
  message(STATUS "Detected OS: Windows")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  add_compile_definitions(PROJ_OS_LINUX)
  message(STATUS "Detected OS: Linux")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
  add_compile_definitions(PROJ_OS_DARWIN)
  message(STATUS "Detected OS: Mac Darwin")
elseif(CMAKE_SYSTEM_NAME STREQUAL "CYGWIN")
  add_compile_definitions(PROJ_OS_CYGWIN)
  message(STATUS "Detected OS: Cygwin")
else()
  add_compile_definitions(PROJ_OS_${CMAKE_SYSTEM_NAME})
  message(STATUS "Unkown OS detected, specified macro for os: PROJ_OS_${CMAKE_SYSTEM_NAME}")
endif()

add_compile_definitions(${CPU_ENDIANNES})
message(STATUS "CPU Endiannes: ${CPU_ENDIANNES}")
